"""
dynamics.py
Canonical discrete-time linearisation of the Dufour autoclave plant.

This is the SINGLE source of truth for the linearised state-space (Ap, Bp) used
to build the per-step MPC-QP. Both the CVXPY/OSQP baseline and the SNN-QP
controller call `linearize(...)`, so the bulk of the model is provably identical
across the two pipelines (previously each hand-coded its own copy, which could
silently drift).

Two regularisation tiers, both documented for reproducibility / deviation
tracking:

  * Tier-2 (always on, mathematically necessary): the cure Jacobian
    J_alpha = f0 * (m/alpha - n/(1-alpha)) has a genuine pole as alpha -> 0
    (since m < 1, f0 * m/alpha ~ alpha^(m-1) -> inf). The derivative simply
    cannot be evaluated at alpha = 0 or 1, so we evaluate it at a point clamped
    to [ALPHA_FLOOR, ALPHA_CEIL]. This regularises the *evaluation point* of the
    derivative, not the resulting finite value. Applied identically in BOTH
    controllers.

  * Tier-3 (opt-in via `trust_region=True`): a bound on the magnitude of the
    exotherm Jacobian contributions injected into Ap. This is NOT physical -- it
    is a trust region on the linearisation. It exists because the SNN-QP uses a
    *condensed* dense prediction (Ap^k over the horizon), and the plant's
    degree-of-cure states are eigenvalue-1 integrators that are UNCONTROLLABLE
    from the autoclave temperature (you cannot un-cure resin). Prestabilisation
    -- the standard remedy for unstable prediction models -- is therefore
    inapplicable, and the un-regularised condensed QP is too ill-conditioned for
    the projection-based SNN solver to keep feasible (verified empirically: it
    diverges to ~1e12). The OSQP baseline solves the sparse form and needs no
    such bound, so it is called with `trust_region=False`. This single, named
    flag is the ONLY modelling difference between the two controllers, and it is
    the honest, documented deviation from a pure first-order linearisation.
"""
import numpy as np
import src.constants as const

ALPHA_FLOOR = 1e-3
ALPHA_CEIL = 0.999
NX = 10  # 3 composite temps + 4 tooling temps + 3 cure states


def linearize(T0_degC, alpha0, trust_region=False):
    """Return (Ap, Bp): the discrete-time linearised plant about (T0, alpha0).

    Parameters
    ----------
    trust_region : bool
        False (baseline): pure first-order model, Tier-2 clamp only.
        True (SNN-QP): additionally bound the exotherm Jacobian terms so the
        condensed dense QP stays solvable by the projection solver. See module
        docstring for the justification.
    """
    Ap = np.zeros((NX, NX))
    Bp = np.zeros(NX)
    T0_K = T0_degC + 273.15

    f0 = const.AC * np.exp(-const.EA / (const.R * T0_K)) * \
        (alpha0 ** const.M_EXP) * ((1 - alpha0) ** const.N_EXP)

    dT = f0 * (const.EA / (const.R * (T0_K ** 2)))
    a_safe = max(ALPHA_FLOOR, min(alpha0, ALPHA_CEIL))     # Tier-2 (necessary)
    da = f0 * ((const.M_EXP / a_safe) - (const.N_EXP / (1 - a_safe)))

    exo_mult = (const.MR * const.DH / const.CPC) * const.TE

    # Exotherm Jacobian contributions -- pure model, or Tier-3 trust-region bound
    if trust_region:
        exo_dT = min(exo_mult * dT, const.FC * 1.8)
        exo_da = float(np.clip(exo_mult * da, -const.FC * 3.0, const.FC * 3.0))
        da_self = (1.0 - 1e-4) + float(np.clip(da * const.TE, -0.90, 0.0))
        dT_cross = float(np.clip(dT * const.TE, 0.0, 0.1))
    else:
        exo_dT = exo_mult * dT
        exo_da = exo_mult * da
        da_self = 1.0 + da * const.TE
        dT_cross = dT * const.TE

    # Composite nodes: heat diffusion + exothermic self-heating
    for i in range(const.NZ_C):
        Ap[i, i] = 1 - 2 * const.FC + exo_dT
        Ap[i, i + 7] = exo_da
        if i == 0:
            Ap[i, i + 1] = 2 * const.FC                    # symmetry axis at the centre
        elif i == const.NZ_C - 1:
            Ap[i, i - 1] = const.FC
            Ap[i, const.NZ_C] = const.FC                   # composite/tooling interface
        else:
            Ap[i, i - 1] = const.FC
            Ap[i, i + 1] = const.FC

    # Tooling nodes: pure heat diffusion; Ta enters at the outer node
    for i in range(const.NZ_C, const.NZ_C + const.NZ_T):
        Ap[i, i] = 1 - 2 * const.FT
        if i == const.NZ_C:
            Ap[i, i - 1] = const.FT
            Ap[i, i + 1] = const.FT
        elif i == const.NZ_C + const.NZ_T - 1:
            Ap[i, i - 1] = const.FT
            Bp[i] = const.FT                                # INPUT: autoclave air Ta
        else:
            Ap[i, i - 1] = const.FT
            Ap[i, i + 1] = const.FT

    # Cure dynamics: alpha depends on alpha and on temperature
    for i in range(7, 10):
        Ap[i, i] = da_self
        Ap[i, i - 7] = dT_cross

    return Ap, Bp


def linearize_trajectory(x0, u_seq, trust_region=False):
    """Return (Ap_seq, Bp_seq): one linearization per horizon step, evaluated
    along a NOMINAL TRAJECTORY generated by rolling the true non-linear plant
    forward under `u_seq`, instead of freezing a single (Ap, Bp) at x0 and
    reusing it for the whole horizon.

    This is the LTV (linear time-varying) prediction named as the principled
    remedy throughout docs/PHASE4_VALIDATION_REPORT.md sections 18-19: the
    frozen-Jacobian LTI prediction cannot see the exotherm burning out as
    alpha -> 1, and measured over-predicts the constrained output by two
    orders of magnitude ten steps ahead during gelation. Re-linearizing at
    each step along an accurate rollout was checked (not merely argued) to
    remove most of that over-prediction: tools/ltv_feasibility_probe.py found
    63.3% of the gradient rows the frozen model flags as violated at six
    stiff states are artifacts of the frozen prediction.

    The rollout uses `src.plant_simulator.AutoclavePlant` -- the SAME
    non-linear model this repo treats as ground truth -- rather than a
    separate, cruder prediction model. This is consistent with the rest of
    the repo: no plant-model mismatch is introduced anywhere else either
    (both controllers already get exact parameter knowledge via `linearize`),
    so using the exact model for the nominal-trajectory rollout does not add
    a new information assumption beyond what the frozen-Jacobian baseline
    already makes -- it only stops discarding curvature the baseline already
    implicitly assumes is knowable. This must be stated plainly wherever LTV
    results are reported: it is a best-case study of what an accurate
    prediction buys, not a claim about what a real air-gapped controller
    could know at runtime.

    Parameters
    ----------
    x0 : array_like, shape (10,)
        Current plant state, ordered [T_comp(3), T_tool(4), alpha(3)] per
        src.plant_simulator.AutoclavePlant.get_state().
    u_seq : array_like, shape (N,)
        Nominal control sequence to roll forward under. Use
        `shift_nominal_sequence` to build this from the previous step's
        solution (receding-horizon shift) or a cold-start hold.
    trust_region : bool
        Forwarded to `linearize` at every step, identically to the LTI path.

    Returns
    -------
    Ap_seq, Bp_seq : list of length len(u_seq)
        Ap_seq[h], Bp_seq[h] is the Jacobian linearizing the transition FROM
        the rollout's step-h state TO step h+1, matching the convention
        `src/qp_builder.py` already uses for its Phi/Gamma row indexing
        (row 0 = x0 itself, row h = the state h steps ahead).
    """
    from src.plant_simulator import AutoclavePlant  # local import: avoids a
    # module-level dependency from dynamics.py (the linearized model) on
    # plant_simulator.py (the non-linear ground truth) for every other caller
    # that only wants the single-point `linearize` above.

    plant = AutoclavePlant()
    plant.T_comp = np.asarray(x0[0:3], dtype=float).copy()
    plant.T_tool = np.asarray(x0[3:7], dtype=float).copy()
    plant.alpha = np.asarray(x0[7:10], dtype=float).copy()

    Ap_seq, Bp_seq = [], []
    for h in range(len(u_seq)):
        state = plant.get_state()
        avg_T = float(np.mean(state[0:3]))
        avg_a = float(np.mean(state[7:10]))
        Ap_h, Bp_h = linearize(avg_T, avg_a, trust_region=trust_region)
        Ap_seq.append(Ap_h)
        Bp_seq.append(Bp_h)
        plant.step(float(u_seq[h]))
    return Ap_seq, Bp_seq


def shift_nominal_sequence(u_seq, u_prev, N):
    """Receding-horizon nominal control sequence for `linearize_trajectory`.

    This is deliberately a SEPARATE concept from either controller's own
    solver warm start (SNNMPCSolver.U_warm, CVXPY's internal warm_start):
    those are solver-internal starting points and are allowed to differ
    between the two controllers, but the nominal trajectory used to generate
    Ap_seq/Bp_seq is part of the shared problem definition -- both
    controllers must compute the identical sequence given the identical
    prior solve, or their QPs stop being comparable (the same rule already
    applied to trust_region / soft_state_constraints / drop_uncontrollable_rows
    in src/qp_builder.py).

    u_seq=None or a stale length (cold start, or after a horizon change)
    holds u_prev across the whole horizon, matching each controller's
    existing `_warm_hold` cold-start convention.
    """
    if u_seq is None or len(u_seq) != N:
        return np.full(N, float(u_prev))
    shifted = np.empty(N)
    shifted[:N - 1] = np.asarray(u_seq[1:], dtype=float)
    shifted[-1] = float(u_seq[-1])
    return shifted
