"""
plant_simulator.py
Non-linear PDE engine calculating the exact physics of the autoclave.
"""
import numpy as np
import src.constants as const

class AutoclavePlant:
    def __init__(self, initial_temp=28.0):
        # State vectors: Temperatures and Degree of Cure (Alpha)
        self.T_comp = np.full(const.NZ_C, initial_temp)
        self.T_tool = np.full(const.NZ_T, initial_temp)
        self.alpha = np.full(const.NZ_C, 1e-5) # Start near 0 to avoid math errors

    def step(self, Ta_input):
        """
        Simulates 60 seconds of real-world physics.
        Takes the current autoclave temperature (Ta) as an input.
        """
        # 1. Calculate Arrhenius Kinetics (Exothermic Reaction)
        T_kelvin = self.T_comp + 273.15 
        dadt = const.AC * np.exp(-const.EA / (const.R * T_kelvin)) * \
               (self.alpha**const.M_EXP) * ((1 - self.alpha)**const.N_EXP)
        
        # Update alpha and cap at 1.0
        alpha_new = self.alpha + dadt * const.TE
        self.alpha = np.clip(alpha_new, 0, 1.0)
        
        # Calculate heat generated by the curing resin
        q_exo = (const.MR * const.DH / const.CPC) * dadt * const.TE

        # Temporary arrays to hold next step values
        T_comp_next = np.zeros(const.NZ_C)
        T_tool_next = np.zeros(const.NZ_T)

        # 2. Heat Transfer in Composite
        for i in range(const.NZ_C):
            if i == 0: # Center
                T_comp_next[i] = self.T_comp[i] + const.FC * (2 * self.T_comp[i+1] - 2 * self.T_comp[i]) + q_exo[i]
            elif i == const.NZ_C - 1: # Surface touching tooling
                T_comp_next[i] = self.T_comp[i] + const.FC * (self.T_comp[i-1] - 2 * self.T_comp[i] + self.T_tool[0]) + q_exo[i]
            else: # Internal
                T_comp_next[i] = self.T_comp[i] + const.FC * (self.T_comp[i-1] - 2 * self.T_comp[i] + self.T_comp[i+1]) + q_exo[i]

        # 3. Heat Transfer in Tooling
        for i in range(const.NZ_T):
            if i == 0: # Touching composite
                T_tool_next[i] = self.T_tool[i] + const.FT * (self.T_comp[-1] - 2 * self.T_tool[i] + self.T_tool[i+1])
            elif i == const.NZ_T - 1: # Touching Autoclave Air (Input Ta)
                T_tool_next[i] = self.T_tool[i] + const.FT * (self.T_tool[i-1] - 2 * self.T_tool[i] + Ta_input)
            else: # Internal
                T_tool_next[i] = self.T_tool[i] + const.FT * (self.T_tool[i-1] - 2 * self.T_tool[i] + self.T_tool[i+1])

        # 4. Update state
        self.T_comp = T_comp_next
        self.T_tool = T_tool_next
        
        return self.get_state()

    def get_state(self):
        """Returns the full 10-variable state vector x_k"""
        return np.concatenate((self.T_comp, self.T_tool, self.alpha))